export default {
  name: `settingsColors`,
  title: `Settings - Company Information`,
  type: `document`,
  // __experimental_actions: [/*'create',*/ 'update', /*'delete',*/ 'publish'],
  fields: [
    {
      name: `settingsColorsName`,
      title: `Company: Name`,
      description: `Add the name of the company. Example: "John Grattan SEO & Web Design" `,
      type: `string`,
      initialValue: `John Grattan SEO & Web Design`,
      // validation: (Rule) => Rule.required(),
    },
    {
      name: `settingsColorsOwner`,
      title: `Company: Owner`,
      description: `Add the owner of the company. Example: "John Grattan"`,
      type: `string`,
      initialValue: `John Grattan`,
      // validation: (Rule) => Rule.required(),
    },
    {
      name: `settingsColorsPhone`,
      title: `Company: Phone Number`,
      description: `Add the company's phone number. Example: "(401) 216-9868"`,
      type: `string`,
      // validation: (Rule) => Rule.required(),
    },
    {
      name: `settingsColorsEmail`,
      title: `Company: Email Address`,
      description: `Add the company's email address. Example: "contact@johngrattan.com"`,
      type: `string`,
      // validation: (Rule) => Rule.required(),
    },
    {
      name: `settingsColorsAddress`,
      title: `Company: Physical Address`,
      description: `Add the company's physical address. Example: "30 Roosevelt Rd, Plymouth, MA 02360"`,
      type: `string`,
      // validation: (Rule) => Rule.required(),
    },
    {
      name: `settingsColorsStreet`,
      title: `Company: Street`,
      description: `Add the company's street. Example: "30 Roosevelt Rd"`,
      type: `string`,
      // validation: (Rule) => Rule.required(),
    },
    {
      name: `settingsColorsCityState`,
      title: `Company: City, State`,
      description: `Add the company's city and state. Example: "Plymouth, MA"`,
      type: `string`,
      // validation: (Rule) => Rule.required(),
    },
    {
      name: `settingsColorsZip`,
      title: `Company: Zip Code`,
      description: `Add the company's zip code. Example: "02360"`,
      type: `string`,
      // validation: (Rule) => Rule.required(),
    },
  ],
};
